modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="breadpack"
version="1.0.0"
displayName="Breadpack"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="naterman90, MCreator"

[[dependencies.breadpack]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



